name: Post-release updates

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types:
      - published
  workflow_dispatch: 
    

jobs:
  post-release-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump patch version
        run: ./scripts/bump-version.sh patch

      - name: Update README with current version
        run: |
          sed -i "s/dev.burnoo:compose-remember-setting:[0-9.]*/dev.burnoo:compose-remember-setting:0.0.1/g" README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: |
            Add post-release updates (`0.0.1`)
          body: |
            Post-release updates:
            - Update README with `0.0.1` version
            - Bump library version to `${{ env.NEW_VERSION }}-SNAPSHOT`
          commit-message: |
            [skip ci] Update version in README and bump to ${{ env.NEW_VERSION }}-SNAPSHOT
          branch: post-release-updates/0.0.1
