name: Post-release updates

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types:
      - published

jobs:
  post-release-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump patch version
        run: ./scripts/bump-version.sh patch

      - name: Update README with current version
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md
          prefix: 'dev.burnoo:compose-remember-setting:'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: |
            Add post-release updates (`${{ github.event.release.tag_name }}`)
          body: |
            Post-release updates:
            - Update README with `${{ github.event.release.tag_name }}` version
            - Bump library version to `${{ env.NEW_VERSION }}-SNAPSHOT`
          commit-message: |
            [skip ci] Update version in README and bump to ${{ env.NEW_VERSION }}-SNAPSHOT
          branch: post-release-updates/${{ github.event.release.tag_name }}
